### ISSUE TITLE
Kirim email verifikasi

### ISSUE THREAD

**Issue by alifirhas** [MaulanaAlirridlo/natsa#5]
Ada masalah saat mengirimkan email menggunan function 
```php
mail()
```
bawaan dari PHP. 

thread yang harus dibaca https://stackoverflow.com/questions/24644436/php-mail-function-doesnt-complete-sending-of-e-mail

yang bisa dilakukan : 
1. gunakan phpmailer
sedang dicoba
2. gunakan mail server 
masih belum diketahui apakah server nantinya akan ada mail server oleh karena itu cara pertama akan dicoba terlebih dahulu

Catatan : 
Tabel pengguna akan ditambah beberapa filed seperti
- vkey -> kunci verfikasi
- verfikasi -> perubahan dari field verikasi yang tadinya enum('terverifikasi, 'tidak terverfikasi') menjadi hanya 0 dan 1

**Comment by alifirhas** [comment]
### PHPMailer

email bisa dikirim dan berhasil **tetapi** akun google si penerima email harus diatur agar bisa login di app yang kurang aman. Sehingga harus tahu bagaimana cara server bisa mengirim email ke akun email pengguna tanpa perlu setting akun google agar dapat login di app yang kurang aman.

**Comment by MrJulian2** [comment]
#Solusi PHPMailer . 
1. Download Source PHPMailer Via GitHub 
2. Membuat akun gmail khusus Web NatSa yang nantinya digunakan sebagai pengirim email kepada pengguna/ user
3. Seting akun gmail NatSa -> akses aplikasi yang kurang aman (aktif)
4. Coding PHPMailer ( Manual ) untuk mengirim email kepada pengguna saat mendaftarkan akun .
